### ISSUE TITLE
Missing Texture on block break

### ISSUE THREAD

**Issue by lesxmore** [tomalbrc/tsa-decorations#4]
I'm using **tsa-decorations-2.1.0+1.21.2-rc1** on 1.21.3 fabric server.
https://github.com/user-attachments/assets/f397edf8-a3bf-4f42-88d6-a2e31b499bbf

**Comment by tomalbrc** [comment]
Thank you for the report ^^
This was an issue with filament, please update filament to the latest version (0.9.7)
